### ISSUE TITLE
Extrair Cedente e Sacado

### ISSUE THREAD

**Issue by lucabfelix** [marquesds/damnboleto#11]
.

**Comment by marquesds** [comment]
Estas informações estão contidas no próprio boleto?

**Comment by lucabfelix** [comment]
.

**Comment by marquesds** [comment]
Como essas informações não seguem um padrão, acredito que não faça sentido tentarmos extraí-las.

**Comment by lucabfelix** [comment]
Está certo. Obrigado.

Em ter, 24 de set de 2019 às 15:15, Lucas Marques <notifications@github.com>
escreveu:

**Comment by lucabfelix** [comment]
Lucas, poderia me dizer se o damnboleto serpa rodaria fora do SO em um
projeto web como o Django? Tenho essa dúvida porque ele tem dependências
como o pdftotext que está em c++

Em ter, 24 de set de 2019 às 15:57, Lucas Barroso <redesocialmeu@gmail.com>
escreveu:

**Comment by marquesds** [comment]
@felixltda, vc precisaria testar pra ver se funciona, mas acredito que sim.

**Comment by felixltda** [comment]
The name Pagar is registered in all countries of South America, including
Brazil as the main country of South America. If you buy this name you will
not be able to use the name Pagar on your logo in any way, understand that.
That is why there is patent. If the owner of this domain has the patent of
the brand, then yes I pay this amount. Otherwise it is not worth 1000 USD
for the risk.

Em ter, 24 de set de 2019 às 16:15, Lucas Marques <notifications@github.com>
escreveu:
